project:
  type: website

website:
  title: "quarto-jupyter-cache-issue-repro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: examples/index.qmd
        text: Examples
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
